name: 'FTP Deploy'
description: 'Automate deploying websites and more with this GitHub action'
author: 'Sam Kirkland'
inputs:
    server:
      required: true
      description: 'ftp server'
    username:
      required: true
      description: 'ftp username'
    password:
      required: true
      description: 'ftp password'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'orange'